### PR TITLE
 Build on win64; update for conda-build3; add maintainers. 

### PR DESCRIPTION
**Pull request by cbrueffer**

### CODE REVIEW

**Comment by cbrueffer** [comment]
@jdblischak @bgruening any idea about this one? I've seen the same error in other recipes as well.

**Comment by jdblischak** [comment]
This is a new one for me. Do you know if we have examples of recipes with the dependency `m2-automake` working on Windows? Looking at Anaconda Cloud, it appears that `m2-automake` does not exist. Instead, the version number is inserted into the package name, e.g. `m2-automake1.15`. Could be worth trying to replace `{{posix}}automake` with `{{posix}}automake1.15` to see if that fixes it.

https://anaconda.org/search?q=m2-automake

Not sure what the best practice is though for selecting the version to use.

**Comment by cbrueffer** [comment]
Seems to work, thanks for the help!

**Comment by cbrueffer** [comment]
@bgruening if you find a minute between GCCBOSC session breaks ;-)

**Comment by bgruening** [comment]
Big break! Sorry, I missed this ping completely.

**Comment by jdblischak** [comment]
@ocefpaf @cbrueffer What is the plan going forward to handle m2-automake? Since m2-automake is only available for Windows, should we just delete that line? Also, is this something that should be fixed upstream, either in `conda skeleton cran` or the helper script?

I'm having the same error in PR https://github.com/conda-forge/r-git2r-feedstock/pull/5

**Pull request merged**
